package: mordred

platform: 
 - linux-64

engine:
 - python=2
 - python=3

script:
  - "[ `git rev-parse --abbrev-ref HEAD` == release ] || sed -i -e 's/$/dev0/' __conda_version__.txt"
  - conda update --all -y
  - conda config --add channels https://conda.anaconda.org/rdkit
  - conda build .

after_success:
  - conda convert /opt/miniconda/conda-bld/linux-64/*.tar.bz2 -p osx-64 -p win-32 -p win-64

build_targets:
  - conda
  - ./osx-64/*.tar.bz2
  - ./win-64/*.tar.bz2
  - ./win-32/*.tar.bz2
