package: mordred
user: mordred-descriptor

platform: 
 - linux-64

engine:
 - python=2.7
 - python=3.4
 - python=3.5

script:
  - python -c "exec(open('mordred/_version.py').read()); print(__version__)" > __conda_version__.txt
  - conda config --add channels rdkit
  - conda config --add channels mordred-descriptor
  - rm -rf .git
  - conda build .

---

platform:
  - win-64

engine:
 - python=2.7
 - python=3.4
 - python=3.5

script:
  - python -c "exec(open('mordred/_version.py').read()); print(__version__)" > __conda_version__.txt
  - conda config --add channels rdkit
  - conda config --add channels mordred-descriptor
  - rd /q /s .git
  - conda build .

build_targets:
  - conda
