language: python

env:
  global:
    - DOC_REMOTE=git@github.com:mordred-descriptor/documentation.git

python:
  - "2.7"
  - "3.4"
  - "3.5"

sudo: false

before_install:
  - eval "$(ssh-agent -s)"
  - ssh-add -D
  - openssl aes-256-cbc -K $encrypted_8d665ddaa7bd_key -iv $encrypted_8d665ddaa7bd_iv -in .id_rsa.enc -out ~/.ssh/.id_rsa -d
  - chmod 600 ~/.ssh/.id_rsa
  - ssh-add ~/.ssh/.id_rsa

  - git config --global user.email "philopon.dependence@gmail.com"
  - git config --global user.name "philopon"

  - if [[ `git rev-parse --abbrev-ref HEAD` != release ]]; then
      sed -i -e 's/$/b0/' mordred/version.txt;
    fi

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  - conda create -c rdkit -c mordred-descriptor -q -n test-environment python=$TRAVIS_PYTHON_VERSION rdkit --file=requirements.txt
  - source activate test-environment
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda install enum34;
    fi
  - pip install coveralls

script:
  - nosetests tests --with-coverage --cover-package=mordred

after_success:
  - set -e
  - coveralls
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.5" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      pip install sphinx sphinxcontrib-bibtex;

      cd docs;
      make html;

      git clone -b gh-pages $DOC_REMOTE gh-pages;
      rm -r gh-pages/$TRAVIS_BRANCH;
      cp -r _build/html gh-pages/$TRAVIS_BRANCH;

      cd gh-pages;
      git add .;
      git commit -m "update documentation to mordred-descriptor/mordred@$TRAVIS_COMMIT";
      git push origin gh-pages;
    fi
