language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

sudo: false
install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  - conda create -c https://conda.anaconda.org/rdkit -q -n test-environment python=$TRAVIS_PYTHON_VERSION rdkit --file=requirements.txt
  - source activate test-environment
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda install enum34;
    fi
  - pip install coveralls

script:
  - nosetests --with-coverage --cover-package=mold

after_success:
  - coveralls
