language: bash

env:
  global:
    - DOC_REMOTE=git@github.com:mordred-descriptor/documentation.git

  matrix:
    - PYTHON_VERSION=3.6
      COVERAGE=true
      DOCUMENTATION=true
    - PYTHON_VERSION=3.5
      COVERAGE=true
    - PYTHON_VERSION=2.7
      COVERAGE=true

os:
  - linux
  - osx

sudo: false

before_install: ./scripts/travis/before_install.sh
install: ./scripts/install.sh
script: ./scripts/test_script.sh
after_success: ./scripts/after_success.sh
