build: off

environment:
  global:
    CYG_ROOT: C:/cygwin

  ANACONDA_CLOUD_TOKEN:
    secure: pc8oWoWVOIURoks1Ha7wHJ0QpWUcjQORf7N3zGa+mSLlXu2uCkL9fEU5w3bvVQGl

  matrix:
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda35-x64
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda-x64
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda

install: '%CYG_ROOT%/bin/bash ./scripts/install.sh'
test_script: '%CYG_ROOT%/bin/bash ./scripts/test_script.sh'
on_success: '%CYG_ROOT%/bin/bash ./scripts/after_success.sh'
