build: off

environment:
  ANACONDA_CLOUD_TOKEN:
    secure: pc8oWoWVOIURoks1Ha7wHJ0QpWUcjQORf7N3zGa+mSLlXu2uCkL9fEU5w3bvVQGl

  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda-x64
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda35-x64
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels rdkit --add channels mordred-descriptor
  - conda install python=%PYTHON_VERSION%
  - if %PYTHON_VERSION% == 2.7 (
      conda install --file requirements.txt enum34
    ) else (
      conda install --file requirements.txt
    )

test_script:
  - nosetests mordred -q

on_success:
  - conda build . --no-test
  - for /f "usebackq delims=" %%v in (`conda build . --output --python %PYTHON_VERSION%`) do set out=%%v
  - anaconda -t %ANACONDA_CLOUD_TOKEN% upload --force %out%
