package:
  name: mordred
  version: 0

source:
  path: .

build:
  number: 0
  script:
    - $PYTHON setup.py install

requirements:
  build:
    - python
    - networkx
    - numpy
    - six
    - rdkit
    - enum34 [py27]
    - tqdm
    - click

    - setuptools
    - pyyaml

  run:
    - python
    - networkx
    - numpy
    - six
    - rdkit
    - enum34 [py27]
    - tqdm
    - click

test:
  imports:
    - mordred

  commands:
    - python -c "from mordred import all_descriptors; all_descriptors()"
    - python -m "mordred.tests"
