package:
  name: mordred
  version: {{load_setup_py_data().version}}

source:
  path: .

build:
  number: 0
  script:
    - python setup.py install

requirements:
  build:
    - python
    - networkx
    - numpy
    - six
    - rdkit
    - enum34 [py27]
    - tqdm

    - setuptools
    - pyyaml

  run:
    - python
    - networkx
    - numpy
    - six
    - rdkit
    - enum34 [py27]
    - tqdm

test:
  imports:
    - mordred

  requires:
    - nose
    - pyyaml

  commands:
    - python -c "from mordred import all_descriptors; all_descriptors()"
    - pip install coveralls
    - nosetests mordred --with-coverage --cover-package=mordred
